version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/:/etc/nginx/conf.d
        ports:
            - "8080:80"
        container_name: test_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        image: php:8.1
        container_name: test_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - postgres

    postgres:
        image: postgres
        restart: always
        volumes:
            - ./tmp/db/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=$DB_USERNAME
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=$DB_DATABASE
        ports:
            - 5433:5432
        container_name: test_db
volumes:
    tmp:
